### ISSUE TITLE
Update to handle new plaid link

### ISSUE THREAD

**Issue by chezky** [jorgefspereira/plaid_flutter#10]
Incredible job on this repo, 

I'm not so familiar with java/swift otherwise I would try to implement this myself, but is there any way you can make a branch to support the latest plaid link requirementes? Thanks!

**Comment by jorgefspereira** [comment]
Hi @chezky,

Thank you. This week I'm going to update the plugin to support the [plaid-link-android 2.1.0](https://github.com/plaid/plaid-link-android/releases/tag/2.1.0) and [plaid-link-ios 1.1.34](https://github.com/plaid/plaid-link-ios/releases/tag/public). Can you be more specific about the latest requirements that you need to be supported? Thanks

**Comment by chezky** [comment]
Plaid has updated their link creation process. Before, you passed in a public token, which products you wanted, and some other configuration info. Now you just create the link with a token created server side. The current plaid documentation should explain this in better detail. Thanks man!

**Comment by jorgefspereira** [comment]
Hi @chezky. Thanks again for the feedback. I've released a new version of the plaid_flutter plugin with the new link_token configuration flow. Please check out the version 1.0.0 and if something is wrong feel free to report the issue.

**Comment by chezky** [comment]
@jorgefspereira incredible job man, thanks for the swift update
