### ISSUE TITLE
Plaid not opening in an add-to-app hybrid model [iOS only]

### ISSUE THREAD

**Issue by prolificcoder** [jorgefspereira/plaid_flutter#103]
Hello we are seeing a strange issue with our[ add-to-app](https://docs.flutter.dev/add-to-app) huge flutter app. Plaid refuses to open, the only relevant error we see is this

```
2023-06-05 14:20:09.457076-0700  [Presentation] Attempt to present <LinkKit.PlaidLinkViewController: 0x7f94221f2d20> on <SoFi_Mobile.RootContainerViewController: 0x7f9462808f00> (from <SoFi_Mobile.RootContainerViewController: 0x7f9462808f00>) whose view is not in the window hierarchy.
```

Note that this issue doesn't happen for a pure flutter flow (with the same exact code) but only if there is a native screen during the route. 

Also it doesn't happen on Android. 

This could be very well be an issue on our side but we are suspecting it could be because this [line](https://github.com/jorgefspereira/plaid_flutter/blob/master/ios/Classes/PlaidFlutterPlugin.m#L161) assumes first class flutter app. 

I am also trying create a pure [reproduce](https://github.com/prolificcoder/samples/pull/1) but would appreciate any thoughts in the meantime.

**Comment by jorgefspereira** [comment]
Hi @prolificcoder. Your sample to reproduce this issue will be extremely useful. I'll take a look into that. Thanks
