### ISSUE TITLE
Double clicking the add account button

### ISSUE THREAD

**Issue by zachary22321** [jorgefspereira/plaid_flutter#105]
This is a feature request.

The user can double click a button and end up having multiple plaid windows open up. I don't think that there is any valid reason to have two plaid browser windows open.

Would it be possible to error out the request if the user has already opened a window?

The way it works now multiple windows will be opened. Then when the user closes one they see another window with an endless spinner.

**Comment by jorgefspereira** [comment]
Hi @zachary22321, what you describe is a valid problem but it goes beyond the purpose of this integration plugin. It's up to the app developer to handle those cases.
