### ISSUE TITLE
Chase Authorization Failure

### ISSUE THREAD

**Issue by KevinSkye1314** [jorgefspereira/plaid_flutter#107]
plaid_flutter version:3.1.2
Sandbox environment can authorize successfully, but the product environment authorization still fails,
Here's a picture of the failure:

![QQ截图20230719112036](https://github.com/jorgefspereira/plaid_flutter/assets/81169336/13542a26-b6e4-41cc-ba35-f22d26607bd1)

**Comment by jorgefspereira** [comment]
Seems to be an issue not related to the flutter plugin itself.
