### ISSUE TITLE
After open Plaid.open(), how to get success callback

### ISSUE THREAD

**Issue by GautamSinghMaurya** [jorgefspereira/plaid_flutter#108]
PlaidLink.open(configuration: configuration).whenComplete(() {
     print("PlaidLink.open:whenComplete");
   }).catchError((onError){
     print("PlaidLink.open:catchError:${onError.toString()}");
   });

    var streamSuccess = PlaidLink.onSuccess;
    var streamExit = PlaidLink.onExit; // on error
    var streamEvent = PlaidLink.onEvent;
    print("streamSuccess");
    print(streamSuccess.forEach((element) {
      print("element.publicToken");
      print(element.publicToken);
      print(element.metadata); // iske andar json public_token ---> keep this token
    }));

**Comment by amitrotner** [comment]
I managed to fix this on Android by sending the `android_package_name` field in the [Create Link Token](https://plaid.com/docs/api/tokens/#linktokencreate) request.
