### ISSUE TITLE
Plugin requiring minSdkVersion 21

### ISSUE THREAD

**Issue by PearlByte** [jorgefspereira/plaid_flutter#11]
Hello,

Thanks for this but I can't seem to get this plugin to work... it requires minSdkVersion 21 instead of 16 and I can't change that because it will break other plugins (like Google Firebase). Is there a way around this? Here's the error...
"Error: uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library"

Thanks,
Ziad
PearlByte

**Comment by chezky** [comment]
@PearlByte   It's not an issue with plaid_flutter but with plaids native iOS and Android implementation. SKK v21 targets Android 5.0. That's a pretty impressive target, and it might be worthwhile allowing your entire app to target 5.0. Otherwise plaid link won't work natively.

**Comment by PearlByte** [comment]
I thought so... ok, thank you for the response. I'll give that a try again.

**Comment by PearlByte** [comment]
Also, do you have a better, more complete example on how to use your plugin? The example included is very simple. I think there are missing initial steps where you need to generate a public_key from a link_key and such... will the plugin handle that?

**Comment by chezky** [comment]
@PearlByte currently only the old method of initializing a plaid link is supported. Using a public key. There is an open issue for this already, and hopefully @jorgefspereira will implement it soon.

**Comment by PearlByte** [comment]
Great! Thanks for the update and thank you for your efforts guys. @chezky @jorgefspereira

**Comment by PearlByte** [comment]
By the way... they no longer provide the public_key in the dashboard. I don't see it there that is why I couldn't use this.

**Comment by jorgefspereira** [comment]
Hi @PearlByte, I didn't know Plaid is no longer providing the public_key to new customers. I've released a new version of the plaid_flutter plugin with the new link_token configuration flow. Please check out the version 1.0.0 and if something is wrong feel free to report the issue.

**Comment by PearlByte** [comment]
@jorgefspereira Thank you so much for the new version! Works perfectly! Great job!!

Only issue I have remaining is updating minSdkVersion to 21 (currently 16) for this plugin... when I change it in the build.gradle file, other plugins complain (like Google's Firebase which wants me to stay at 16). Any idea how I can upgrade my plugins to be ok with minSdkVersion 21 so that this plugin would play nice with all the others? Thanks in advance.

**Comment by PearlByte** [comment]
After re-creating my whole project from scratch and rebuilding it gradually with all my packages, it seems to be working. I ended up removing the **firebase_core** package for now and just sticking to firebase_auth that I need. Very weird issue but seems it is just not compatible with this Plaid package. I do have my minSdkVersion set to 21 now (instead of 16) and I'm targeting the latest sdk 28 and 29. Thanks anyway @jorgefspereira !

**Comment by jorgefspereira** [comment]
I'm going to take a look to the firebase_core weird issue. See if I can replicate here and check the incompatibility issue. Thanks again @PearlByte. Feel free to report any issues, I'll try to fix them as soon as possible.
