### ISSUE TITLE
PlaidLink.open error

### ISSUE THREAD

**Issue by ageofadz** [jorgefspereira/plaid_flutter#111]
Hi, I am encountering an exception when passing a configuration object containing a link token generated using plaid's sandbox endpoint. I am testing in the browser.

I am successfully generating the token on my backend and passing it into to my flutter app, and generating the token like so:
`_configuration = LinkTokenConfiguration(token: token);` (token being the string extracted from my server's response)
This configuration object is passed into `PlaidLink.open(configuration: _configuration!)`.

When I debug `plaid_flutter_web.dart` in this package, the `options` object is successfully populating with my token on line 75, but on line 95, I see the `_plaid` object populated with `Error: LateInitializationError: Field '_plaid' has not been initialized.` after `create()` is called on it.
The error I get ultimately is `ChromeProxyService: Failed to evaluate expression 'Plaid.create': TypeError: Cannot read properties of undefined (reading 'create').`

Since the `create` function comes from the JS library, I can't see where it's failing or get any insight to the error. Has anyone else encountered this?

Thanks!

**Comment by afc-development** [comment]
Same issue here. Not able to further deduce what might be causing this issue.

**Comment by ageofadz** [comment]
In the meantime, I've been taking a crack at integrating Plaid into my app through a webview:
https://plaid.com/docs/link/webview/

Obviously using a webview over an interface built for the native mobile UI comes with tradeoffs, but hopefully this solution can get the ball rolling for people who are encountering this problem and it's blocking them.

**Comment by andson-keeper** [comment]
Were you guys able to solve this issue?

**Comment by ageofadz** [comment]
Not yet - as far as this issue is concerned, I'm not sure if it's limited to using the chrome build of the app or if it will persist in iOS or Android. The answer probably lies in Plaid's JS library where the `create` function is defined.

The project I'm using this for is on pause but I would recommend trying the plaid webview I linked above, and embedding it into the interface you're putting together in Flutter. If anyone gives that a shot let us know how it goes.

**Comment by jorgefspereira** [comment]
I'll try to take a look at this issue this weekend.

**Comment by andson-keeper** [comment]
I was having this issue because I was missing the `<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>`
 in my index.html file

**Comment by jorgefspereira** [comment]
Yeah. I tested over the weekend and only got a similar error when the <script> import wasnt there. Glad you fixed the issue. I'm wrapping up an update to the plugin and then I'll close this issue.
