### ISSUE TITLE
Export PlaidPlatformInterface

### ISSUE THREAD

**Issue by MauriMiguez** [jorgefspereira/plaid_flutter#114]
Im trying to do some unit tests on my code but im unable to mock the `PlaidPlatformInterface` because is not being exported in the package nor there is another package available where it is exported.

Normally when working with PlatformInterface implementations, even though they mostly contain static methods, I mock the PlatformInterface class so I am able to do unit testing on the class im implementing.

Unfortunately plaid_flutter does no expose it's `PlaidPlatformInterface` nor is being exported in another package so im unable do unit testing on my code. If there is an other way I could be mocking the plaid sdk let me know but I didn't find any other way around it.

Could `PlaidPlatformInterface` class be added to the export file so folks can easily mock while doing unit tests?

**Comment by jorgefspereira** [comment]
Hi @MauriMiguez, I added the export for the PlaidPlatformInterface. Would be great to have some unit tests on this integration plugin. Feel free to PR some of them :)
