### ISSUE TITLE
institutionName is null

### ISSUE THREAD

**Issue by chezky** [jorgefspereira/plaid_flutter#12]
Just switched to v1.1.0, seems like institutionName is always null on android.

```
onSuccess: public-sandbox-9ee3e81a-6918-48f1-953d-b553515a4738, metadata: linkSessionId: 73ed0508-2952-4a5b-94c3-682a2468425a, institutionId: null, institutionName: null, accounts:
```

Running in sandbox mode

**Comment by jorgefspereira** [comment]
Hi @chezky, thank you for the issue report. The institution metadata was indeed not parsed properly on Android. I have released a new version of the plugin (1.1.1) fixing the issue.
