### ISSUE TITLE
Exception when doing import on web

### ISSUE THREAD

**Issue by almovsesanso** [jorgefspereira/plaid_flutter#120]
The current version of the plugin is broken when used to do import from the web because it's not populating the `environment` parameter which the plaid JS is still expecting. It fails 100% of the time.

![image](https://github.com/jorgefspereira/plaid_flutter/assets/125292983/0d0af052-ec17-4720-a1ae-ec8a4bf3ed92)

The fix is one-liner here, I had to fork the repo and manually apply it to get unblocked. Please apply the same or a similar fix to unblock the web import scenario.

<img width="1172" alt="image" src="https://github.com/jorgefspereira/plaid_flutter/assets/125292983/cf1982ff-2f2d-4bd6-b236-3b505ec360b5">

**Comment by jhionan** [comment]
what version are you talking about? We are using 3.1.5 in prod for mobile / web, it's working. Can you provide more details?

**Comment by almovsesanso** [comment]
It repros on 3.1.3 but also on 3.1.5

I think the reason you're not seeing it because you don't have `Uncaught Exceptions` turned on in VS Code or Chrome. If you turn that setting on you'll see the exception. We need to set `options.env` to make the exception not happen.

<img width="616" alt="image" src="https://github.com/jorgefspereira/plaid_flutter/assets/125292983/1dc903d3-061a-4d2a-ac01-867cb73ac69e">

When it happens the error is always the same about incorrect `environment` which makes sense because in `link-initialize.js` the `getApiUrl` function expects to have environment but it's getting null since we're passing `LinkConfiguration` and not `LegacyLinkConfiguration`.

This is screenshot of the exception from 3.1.5 with some more information.

<img width="904" alt="image" src="https://github.com/jorgefspereira/plaid_flutter/assets/125292983/1293e158-2488-4247-9b37-2048c0e79af4">

This is stacktrace from the browser when the error happens. You can see the value of `t` is null here and throws an exception.

<img width="902" alt="image" src="https://github.com/jorgefspereira/plaid_flutter/assets/125292983/8b59c676-d2a2-400e-8bb7-12870039d9c9">

**Comment by jhionan** [comment]
@almovsesanso I could verify this issue, do you want to create a PR for us?

**Comment by almovsesanso** [comment]
> @almovsesanso I could verify this issue, do you want to create a PR for us?

Sure. How to create a PR for you?

**Comment by jorgefspereira** [comment]
@almovsesanso thank you for the report and fix. I'll publish a new release with it
