### ISSUE TITLE
Not receiving HANDOFF events when linking an account

### ISSUE THREAD

**Issue by zdutra** [jorgefspereira/plaid_flutter#125]
On April 3rd around 8pm Central time, we stopped receiving HANDOFF events from Plaid on iOS specifically. Here are some example logs along with a session id. I removed the public token at the end for privacy. We have validated this behavior on both version 3.1.1 and 4.0.3.

Repro steps:
1. open demo app
2. provide valid link token
3. proceed to link an account
4. observe no HANDOFF event mentioned in logs

flutter: onEvent: TRANSITION_VIEW, metadata: viewName: CONSENT, exitStatus: , mfaType: , requestId: 7hek1QLXY6xCY6y, timestamp: 2024-04-10T14:57:19Z, linkSessionId: da198e99-4fff-4357-b87f-6840c84affdb, institutionId: , institutionName: , institutionSearchQuery: , errorType: , errorCode: , errorMessage: ,  selection: null, routingNumber: null, matchReason: null, accountNumberMask: null
f
lutter: onEvent: OPEN, metadata: viewName: CONSENT, exitStatus: , mfaType: , requestId: 7hek1QLXY6xCY6y, timestamp: 2024-04-10T14:57:19Z, linkSessionId: da198e99-4fff-4357-b87f-6840c84affdb, institutionId: , institutionName: , institutionSearchQuery: , errorType: , errorCode: , errorMessage: ,  selection: null, routingNumber: null, matchReason: null, accountNumberMask: null

flutter: onEvent: TRANSITION_VIEW, metadata: viewName: SELECT_INSTITUTION, exitStatus: , mfaType: , requestId: reMmMmqlcMhNLoI, timestamp: 2024-04-10T14:57:22Z, linkSessionId: da198e99-4fff-4357-b87f-6840c84affdb, institutionId: , institutionName: , institutionSearchQuery: , errorType: , errorCode: , errorMessage: ,  selection: null, routingNumber: null, matchReason: null, accountNumberMask: null

flutter: onEvent: SELECT_INSTITUTION, metadata: viewName: , exitStatus: , mfaType: , requestId: reMmMmqlcMhNLoI, timestamp: 2024-04-10T14:57:27Z, linkSessionId: da198e99-4fff-4357-b87f-6840c84affdb, institutionId: ins_116944, institutionName: Sallie Mae, institutionSearchQuery: null, errorType: , errorCode: , errorMessage: ,  selection: null, routingNumber: null, matchReason: null, accountNumberMask: null

flutter: onEvent: TRANSITION_VIEW, metadata: viewName: CREDENTIAL, exitStatus: , mfaType: , requestId: UvcVfcHuM0zRfWd, timestamp: 2024-04-10T14:57:27Z, linkSessionId: da198e99-4fff-4357-b87f-6840c84affdb, institutionId: ins_116944, institutionName: Sallie Mae, institutionSearchQuery: , errorType: , errorCode: , errorMessage: ,  selection: null, routingNumber: null, matchReason: null, accountNumberMask: null

flutter: onEvent: SUBMIT_CREDENTIALS, metadata: viewName: , exitStatus: , mfaType: , requestId: UvcVfcHuM0zRfWd, timestamp: 2024-04-10T14:57:33Z, linkSessionId: da198e99-4fff-4357-b87f-6840c84affdb, institutionId: ins_116944, institutionName: Sallie Mae, institutionSearchQuery: , errorType: , errorCode: , errorMessage: ,  selection: null, routingNumber: null, matchReason: null, accountNumberMask: null

flutter: onEvent: TRANSITION_VIEW, metadata: viewName: SELECT_ACCOUNT, exitStatus: , mfaType: , requestId: lelqbJNhtwRbyhj, timestamp: 2024-04-10T14:57:34Z, linkSessionId: da198e99-4fff-4357-b87f-6840c84affdb, institutionId: ins_116944, institutionName: Sallie Mae, institutionSearchQuery: , errorType: , errorCode: , errorMessage: ,  selection: null, routingNumber: null, matchReason: null, accountNumberMask: null

flutter: onEvent: TRANSITION_VIEW, metadata: viewName: CONNECTED, exitStatus: , mfaType: , requestId: u7bNumIDNX4zwbD, timestamp: 2024-04-10T14:57:37Z, linkSessionId: da198e99-4fff-4357-b87f-6840c84affdb, institutionId: ins_116944, institutionName: Sallie Mae, institutionSearchQuery: , errorType: , errorCode: , errorMessage: ,  selection: null, routingNumber: null, matchReason: null, accountNumberMask: null

flutter: onSuccess: institution.id: ins_116944, institution.name: Sallie Mae, accounts: [id: P3xMqpqy1qfnnEljrJErHxDbjaaw4dCoyej9g, mask: 0000, name: Plaid Checking, type: depository, subtype: checking, verification_status: null][id: jy9MAVAe4AhbbMyZ35M3hk4nPeebvEc6R79BB, mask: 1111, name: Plaid Saving, type: depository, subtype: savings, verification_status: null][id: 7Zx1BABJnBS88QX1NZQNiGZzRAApdrfdB53mK, mask: 2222, name: Plaid CD, type: depository, subtype: cd, verification_status: null][id: eAGjoVoqBotoo35Lby3bioRvDbbax3ir3bPz1, mask: 3333, name: Plaid Credit Card, type: credit, subtype: credit card, verification_status: null][id: Qxd1KoKeLKSnnQqzGdQGHypBdllnXoHwlgBJ7, mask: 4444, name: Plaid Money Market, type: depository, subtype: money market, verification_status: null][id: ZQZKNVNxnNInny4LJ1yJHZeVb55AmLce1EWNl, mask: 5555, name: Plaid IRA, type: investment, subtype: ira, <…>

**Comment by zdutra** [comment]
@jorgefspereira when you have a chance, do you mind looking into this issue?

**Comment by KevinSkye1314** [comment]
I'm facing the same issue. Is there a current solution available?

**Comment by dtroupe-plaid** [comment]
> we stopped receiving HANDOFF events from Plaid on iOS specifically

I suspect the issue has to due with the retention of the `Handler` on iOS. I recently resolved the issue in the React Native SDK with [this pull request](https://github.com/plaid/react-native-plaid-link-sdk/pull/654/files#diff-c05ecb815bd3388a9a81321848915a29c450c3522aa907f73f2582276954501fR104) we had to stop deleting the handler when we received `onSuccess` and retain it until `HANDOFF` was received. 

I am not sure exactly how this situation is handled in this SDK, but if it's similar this solution will likely work as well.

**Comment by jorgefspereira** [comment]
I’m going to take a look at this issue.

Thank you @dtroupe-plaid for the tip

**Comment by dtroupe-plaid** [comment]
This [pull request](https://github.com/jorgefspereira/plaid_flutter/pull/128) should resolve it.

**Comment by lzapar2** [comment]
@dtroupe-plaid thank you for chiming in! @jorgefspereira once the fix is verified, can you also apply it on top of 3.1.x so that us on the older version call pull it in without a major upgrade? Thank you!
