### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by slauzinho** [jorgefspereira/plaid_flutter#13]
Some institutions use an OAuth authentication flow, does the library offer support for those orgs?

According to their docs once you get the oauth_state_id from the url params you need to dismiss the old Link object and create a new one and pass the oauth_state_id to the new config.

**Comment by jorgefspereira** [comment]
Hi @slauzinho

Yes OAuth is supported. You have on the LinkConfiguration object the properties `oauthRedirectUri ` and `oauthNonce` to initially launch Link. The `oauthStateId` can also be passed to complete the authentication flow.

I'm closing this issue. If you find any issue with the plugin feel free to report it.

**Comment by slauzinho** [comment]
Hey @jorgefspereira I know you can pass the `oauthRedirectUri ` and the `oauthNonce` the issue is that when you first call `plaid.open()` with your `oauthRedirectUri` and `oauthNonce` you need to close the old plaid window and call `plaid.open()` again with the `oauthStateId`.  

Do you know how I can implement this?

**Comment by jorgefspereira** [comment]
Indeed is missing a dismiss method to be able to re-launch the framework. Thank you for the report. I'll submit tomorrow version 1.1.2 with a close method and then you just need to update the LinkConfiguration object and open again.

**Comment by jorgefspereira** [comment]
Hi @slauzinho. Version 1.1.2 is live. Thank you again for the issue report. Any other feedback is always welcome.

**Comment by slauzinho** [comment]
@jorgefspereira Thank you for your amazing lib and support
