### ISSUE TITLE
depreciated build.gradle dependencies

### ISSUE THREAD

**Issue by morgantstewart** [jorgefspereira/plaid_flutter#130]
The plugin dependencies listed in the package build.gradle file are currently depreciated and throws depreciation warnings every time project is run. Currently we are manually updating these dependencies by editing their versions listed in the build.gradle file for the package. Any update appreciated as it is halting our production.

**Comment by jorgefspereira** [comment]
I've updated gradle tools, so this issue should be fixed. Fell free to reopen if needed.
