### ISSUE TITLE
Feature request: support for submit() and preload methods

### ISSUE THREAD

**Issue by phoenixy1** [jorgefspereira/plaid_flutter#131]
Plaid recently introduced two new features for Link:

1. The submit() method is used to support the new Layer product
2. A new two-step loading paradigm has been added, where Link is first created and then opened -- this model was always available on iOS, but it is now available on Android as well. This is handy for all users of the mobile SDKs, because it speeds up loading time for Link by allowing you to "warm up" the Link configuration before presenting the Link UI, and it's mandatory for Layer users.  You can see docs about it here: https://plaid.com/docs/link/android/#create-a-linktokenconfiguration and the sample apps in our SDKs have been updated to use it: https://github.com/plaid/plaid-link-android

Any chance you would be able to add these in Flutter? It would be much appreciated!

**Comment by Parfyonator** [comment]
That would be a really great addition to this plugin. @jorgefspereira any chance it is coming soon in the nearest release?

**Comment by jorgefspereira** [comment]
Sure. I'll add the submit method to support the new product.

**Comment by Parfyonator** [comment]
Hi @jorgefspereira. Don't want to be annoying, but when are you hoping to add this functionality? I just want to know if it will be added in about a month or I should figure out how to do it myself for my project I'm currently working on. Thanks in advance.

**Comment by jorgefspereira** [comment]
I'm targeting for this week 👍

**Comment by Parfyonator** [comment]
Hi @jorgefspereira. Just want to let you know about one thing. I was having trouble generating a token with Layer product being one of the products in the list (Sandbox environment) and therefore I contacted Plaid support regarding this issue. From my conversation I understood that Layer is currently in beta and will be fully functional in upcoming months. So if you facing the same issue don't be frustrated. Probably that's the expected behaviour.

**Comment by phoenixy1** [comment]
Actually, @Parfyonator has a good point -- @jorgefspereira if you need your account to be enabled for the layer beta in order to test or implement this, send me your client ID and I'll get you enrolled in the beta program. You can reach me on the Discord (https://discord.gg/EQrabFrH) or via email at ahoffer@plaid.com.

**Comment by jorgefspereira** [comment]
I've been sick these days but its only missing testing to this new feature. Hopefully next week I'll be able to release.

**Comment by Pexeed** [comment]
Hello, any updates on this? Would really help me out to have this implemented, is it implemented in the latest version?

https://github.com/jorgefspereira/plaid_flutter/releases/tag/4.0.6-rc

**Comment by jorgefspereira** [comment]
I've updated the plugin with new funcionality. Feel free to report any issue or submit a PR. 

Sorry for taking so long. I'll try to fix/improve the lib more quickly.

**Comment by Jeidoban** [comment]
> I've updated the plugin with new funcionality. Feel free to report any issue or submit a PR.
> 
> Sorry for taking so long. I'll try to fix/improve the lib more quickly.

Hi there, I don't think you owe anybody updates to this repo. You are absolutely amazing for maintaining this, but I imagine you have other priorities that come first. You've certainly made my life a lot easier with this as I don't have to finagle with platform specific code, but please look after yourself first and update when you feel like and have the time. And if you don't then I'm sure one of the many folks that use this incredible package can PR it themselves.

Thank you again for this, it's honestly pretty frustrating that Plaid doesn't have official Flutter support at this point.
