### ISSUE TITLE
how to create a link token?

### ISSUE THREAD

**Issue by kaarens93** [jorgefspereira/plaid_flutter#16]
Not an issue with this package but I'm having a lot of trouble creating a link token and I was hoping for some guidance. I've read the plaid documentation but it doesn't help at all. I tried using cloud functions. I'm using nodejs and I installed the plaid npm package so that I can use createLinkToken(). Does the /link/token/create endpoint need to be in my cloud function? I tried that but nothing works. Please advise

Thank you for an awesome package, btw

**Comment by kaarens93** [comment]
Nvm I figured it out!

**Comment by KelvinForteta** [comment]
Could you pls guide me through the process of creating a link token?

**Comment by kaarens93** [comment]
sure, I'm using dio package to make the http call. My code looks like: 
`
    Response resp =
        await dio.post('https://sandbox.plaid.com/link/token/create', data: {
      'client_id': xxx,
      'secret': xxx,
      'user': {'client_user_id': xxx},
      'client_name': xxx,
      'products': ['auth'],
      'country_codes': ['US'],
      'language': 'en',
      'android_package_name': xxx,
    });   
`
`
var linkToken = resp.data['link_token'];
`

This should give you a good start on what to do. Read the documentation for what to fill in for xxx. Also for ios, you don't need  'android_package_name'.
