### ISSUE TITLE
verificationStatus is allways NULL

### ISSUE THREAD

**Issue by tan-nad** [jorgefspereira/plaid_flutter#17]
Since the version 1.1.4 `verification_status` is added on success callback, but the value is always NULL although using **Same Day Micro-deposits** flow.

I think should add `aux.put("verification_status", a.getVerificationStatus());` after this line for android
https://github.com/jorgefspereira/plaid_flutter/blob/master/android/src/main/java/com/github/jorgefspereira/plaid_flutter/PlaidFlutterPlugin.java#L290

**Comment by jorgefspereira** [comment]
Thank you for the report. Fixed and released version 1.1.5.
