### ISSUE TITLE
[feature request] onExit callback should return error_code

### ISSUE THREAD

**Issue by kaarens93** [jorgefspereira/plaid_flutter#18]
Currently onExit returns an error message (for example: "the provided credentials were not correct") that doesn't look anything in the official plaid documentation. It would be more useful to return error data such as what's returned in the onEvent callback like error_type, error_code, error_message (but error_code is sufficient). 

Thanks for a great package :)

**Comment by jorgefspereira** [comment]
hi @kaarens93, thank you for your suggestion. I'll improve the return error message after I finish the migration to the plaid 3.x sdk. Thank you

**Comment by jorgefspereira** [comment]
The onExit function on the new version 2.0.0 returns a LinkError with all the error data. Feel free to report any issue.
