### ISSUE TITLE
onSuccess MetaData: null account.id

### ISSUE THREAD

**Issue by smangat2017** [jorgefspereira/plaid_flutter#23]
Since the new rollout of [Plaid link](https://blog.plaid.com/the-all-new-plaid-link/), the account.id in the metadata variable passed into onSuccess has been null for me. Name, mask, and type are all there...no id though!

Running on iOS.

**Comment by oshuam** [comment]
Seeing the same issue. Seems to be a recent problem with the iOS SDK (LinkKit). It apparently was solved on version 1.1.38 (https://github.com/plaid/plaid-link-ios/releases/tag/ios%2F1.1.38) but plaid_flutter is using 1.1.36 https://github.com/jorgefspereira/plaid_flutter/blob/master/ios/plaid_flutter.podspec

**Comment by jorgefspereira** [comment]
Hi @smangat2017 @oshuam. I just updated the plugin to 1.1.6 which includes the new iOS LinkKit 1.1.38 that should fix the account.id onSuccess callback.

**Comment by smangat2017** [comment]
Awesome! Thanks @jorgefspereira. Much appreciated!
