### ISSUE TITLE
web support

### ISSUE THREAD

**Issue by ayushin** [jorgefspereira/plaid_flutter#27]
Hi,

Adding web support should be trivial. Is anybody working on it already?

There's an implementation already that could be merged perhaps?

https://github.com/firelab-app/plaid_link/blob/master/lib/plaid_link_web.dart

**Comment by jorgefspereira** [comment]
Hi @ayushin, I'll add web support by the end of the year.

**Comment by ayushin** [comment]
how's the progress on this?

**Comment by jorgefspereira** [comment]
I hope next week I'll have a new version of the plugin with web support.

**Comment by jorgefspereira** [comment]
Web support released on version 2.0.0. Feel free to report any issue.
