### ISSUE TITLE
Futures instead of callbacks

### ISSUE THREAD

**Issue by pelanmar1** [jorgefspereira/plaid_flutter#29]
It would be great if the open function would return a future with the linkToken instead of having to specify the onSuccess/onError callbacks. Any ideas on how this could be solved? 

Thanks

**Comment by malithkuruppu** [comment]
> It would be great if the open function would return a future with the linkToken instead of having to specify the onSuccess/onError callbacks. Any ideas on how this could be solved?
> 
> Thanks

I too agree if there is a possibility to  return a future with the linkToken!
