### ISSUE TITLE
[iOS][LinkSuccessMetadata] Missing verification status

### ISSUE THREAD

**Issue by tan-nad** [jorgefspereira/plaid_flutter#32]
`verification_status` is returned NULL on iOS (using Same Day Micro-deposits flow in sandbox mode).
and the value of `institutionId` is also different, it is empty on Android and NULL on iOS.

**Android**

> linkSessionId: <LINK_SESSION_ID>, **institutionId**: , institutionName: null, accounts: [id: <ACCOUNT_ID>, mask: 0000, name: Checking ...0000, type: depository, subtype: checking, **verification_status**: **pending_manual_verification**]

**iOS**
> linkSessionId: <LINK_SESSION_ID>, **institutionId**: **null**, institutionName: null, accounts: [id: <ACCOUNT_ID>, mask: 0000, name: Checking ...0000, type: depository, subtype: checking, **verification_status**: **null**]

Please let me know if I can provide you with any further information

**Comment by tan-nad** [comment]
I checked with the latest commit and somehow this issue is solved.
Any plan when new version is released?

**Comment by jorgefspereira** [comment]
hi @tan-nad,

Yes I'm releasing this week a new version. I had a couple of delays but everything is on track for this week

**Comment by jorgefspereira** [comment]
New version released 2.0.0. Feel free to report any issue.
