### ISSUE TITLE
Unsure how to generate link token following the steps

### ISSUE THREAD

**Issue by mikeyyg96** [jorgefspereira/plaid_flutter#34]
I tried using the Legacy but I think it has been removed ever since the update, and following their documentation has not given me luck. I was hoping if anyone would share the steps they did to get the token.

**Comment by jorgefspereira** [comment]
Hi @mikeyyg96, the plugin still supports the legacy configuration but for new plaid accounts the public_key is not being generated. The link_token should be created by your app's server and passed to your app's client through an endpoint. [Here](https://plaid.com/docs/link/link-token-migration-guide/#update-your-server) you can find an example of how you should update your app's server to support the creation of a link_token. I hope this answer your question.
