### ISSUE TITLE
Crash on iOS when open with Public Key

### ISSUE THREAD

**Issue by hoangphat258** [jorgefspereira/plaid_flutter#44]
When I open with Public Key on iOS, it crashes without any information. It works fine on Android

**Comment by jorgefspereira** [comment]
hi @hoangphat258, can you provide the error log and the flutter doctor information? I've tested with my public key on the plugin example and works fine.

**Comment by hoangphat258** [comment]
Thank you for replying
- Here is the error log:
-[NSNull _fastCStringContents:]
: unrecognized selector sent to instance 0x1e5903ad8
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull _fastCStringContents:]
: unrecognized selector sent to instance 0x1e5903ad8'
*** First throw call stack:
(0x1a4ac55f0 0x1a47e7bcc 0x1a49c9ea8 0x1a4ac9694 0x1a4acb5bc 0x1b2097618 0x1b20977bc 0x1dadc42cc 0x1042a0de4 0x1042a0730 0x1042a11b8 0x10313dd18 0x10313d94c 0x106ea4694 0x106644038 0x10694341c 0x1068e281c 0x1068e4ed4 0x1a4a441c0 0x1a4a43edc 0x1a4a435b8 0x1a4a3e5c8 0x1a4a3dc34 0x1aeb8738c 0x1a8b7022c 0x10293cf54 0x1a48c5800)
libc++abi.dylib: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001a48bad88 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1a48bad88 <+8>:  b.lo   0x1a48bada4               ; <+36>
    0x1a48bad8c <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1a48bad90 <+16>: mov    x29, sp
    0x1a48bad94 <+20>: bl     0x1a4899ad0               ; cerror_nocancel
Target 0: (KARD) stopped.

- Here is my flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.2 20D80 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by do-lokesh** [comment]
Hi @hoangphat258 , are you able resolve this ?, if YES,  Pls let us know, How did you do that.

**Comment by hoangphat258** [comment]
Hi @do-lokesh , I used method channel to resolve this and it works fine

**Comment by do-lokesh** [comment]
@hoangphat258 , Pls share any links here. that will be very helpful. Thank you.

**Comment by hoangphat258** [comment]
https://docs.flutter.dev/development/platform-integration/platform-channels
I used native plaid link and used method channel to receive the result

**Comment by jorgefspereira** [comment]
I was unable to replicate this issue. Is it still happening?

**Comment by jorgefspereira** [comment]
@hoangphat258 if you can replicate, can you provide a pull request with a fix?
