### ISSUE TITLE
Unable to continue with Oauth result

### ISSUE THREAD

**Issue by lsauss2** [jorgefspereira/plaid_flutter#45]
Hi,

I am using this plugin which works great but I am currently trying to implement Oauth.
I am using the Token Configuration for my Link workflow.

Everything is setup with App Links, the bank's webpage opens and comes back in my App with the "Oauth_state_id" appended to the URI.

However, I do not know what to do with it to continue the Link process once I have it.

I have noticed that the Link iOS SDK exposes a "continue" method to pass the redirectURI with but such method is not exposed in this plugin.

Can you please help me?

I tried to 

Thanks

**Comment by lsauss2** [comment]
I made it work by exposing the "continueFromRedirectUri" in the plugin and passing the URI I received back from my App Link in JSON format.

Any reason why the "continue" method is not exposed in the plugin?

**Comment by jorgefspereira** [comment]
Hi @lsauss2, indeed the "continueFromRedirectUri" method is not exposed. I have fixed the issue and a new version (2.1.2) of the plugin will be live today. 👍

**Comment by lsauss2** [comment]
Amazing! Thanks for putting together a great library

**Comment by ndahlquist** [comment]
@lsauss2 @jorgefspereira , any chance either of you could provide the code snippet for where/how you are calling `continueFromRedirectUri`? A few of us over at https://github.com/jorgefspereira/plaid_flutter/issues/55 would appreciate it.

I tried calling this when I receive the deeplink URL in `onGenerateRoute`, but am getting crashes in the Plaid SDK.

If we get this working, I'm happy to volunteer to contribute documentation or add to the example app 🙂
