### ISSUE TITLE
Plaid Link opens briefly and closes with error. "Error: Invalid env: "tartan"

### ISSUE THREAD

**Issue by codyfilatov** [jorgefspereira/plaid_flutter#49]
"Error: Invalid env: "tartan". env must be "sandbox", "development" or "production"."

This is the error I am receiving. I have looked through the code and do not have a way to forcibly provide these details. It is important to note that SOMETIMES it works fine and Link opens properly. But 50% of the time it fails to open with this error.

I am also receiving errors related to font
Access to font at 'https://cdn.plaid.com/link/2.0.1097/assets/fonts/cern-regular.woff2' from origin 'https://secure.plaid.com' has been blocked by CORS policy:

Would like some better understanding on what can be done to ensure Plaid Link opens everytime successfully.
I am currently using Plaid in development mode.

**Comment by codyfilatov** [comment]
Another note. In sandbox, plaid link works fine. This only occur in development

**Comment by jorgefspereira** [comment]
I was unable to reproduce the error. Please give a try to the new version 2.1.4 and test your development key in the example app provided.

**Comment by PrabavathiKalidoss** [comment]
We are using plaid_flutter: ^2.2.0 version.But we still have a issue on android version 8 like,
Access to font at 'https://cdn.plaid.com/link/2.0.1097/assets/fonts/cern-regular.woff2' from origin 'https://secure.plaid.com/' has been blocked by CORS policy

Help me to fix this issue.
