### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method open on channel plugins.flutter.io/plaid_flutter)

### ISSUE THREAD

**Issue by stephaniemartin** [jorgefspereira/plaid_flutter#5]
I am using v0.2.2
I got this error when build on android:
Unhandled Exception: MissingPluginException(No implementation found for method open on channel plugins.flutter.io/plaid_flutter)

I've added this on build.gradle:

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

I have set the minimum api to 21.
in iOS it built and works fine.

in main/java/io/flutter/plugins/GeneratedPluginRegistrant.java plugin has been registered.

what am I doing wrong?

thank you

**Comment by jorgefspereira** [comment]
Thanks for reporting. Can you check these questions list here [flutter/flutter#10912 (comment)](https://github.com/flutter/flutter/issues/10912#issuecomment-310499594)

**Comment by jorgefspereira** [comment]
Closing the issue due to lack of response.
