### ISSUE TITLE
Error on Open

### ISSUE THREAD

**Issue by netgfx** [jorgefspereira/plaid_flutter#50]
I'm testing with sandbox, got the `link_token` from the backend, but when running `.open()` I'm getting

`Unable to create PLKHandler due to: The operation couldn’t be completed. (com.plaid.link error 0.)`

on iOS. Any ideas?

**Comment by jorgefspereira** [comment]
I was unable to reproduce the error. Please give a try to the new version 2.1.4 and try to replicate the error in the example app.

**Comment by netgfx** [comment]
Sorry for not responding earlier, the issue was a malformed link token (however an error on the Flutter side woudn't be bad, so we could handle it properly)
