### ISSUE TITLE
Integration of plaid working fror android but crashing app on ios

### ISSUE THREAD

**Issue by arslankaleem7229** [jorgefspereira/plaid_flutter#54]
I am working with plaid but its crashing on ios. Error is posted below:
```

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
lib/main.dart:1
Xcode build done.                                           13,1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/abcdefg/Code/flutter/.pub-cache/hosted/pub.dartlang.org/plaid_flutter-2.1.4/ios/Classes/PlaidFlutterPlugin.m:3:9: fatal error: 'LinkKit/LinkKit.h' file not found
    #import <LinkKit/LinkKit.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: the following command failed with exit code 1 but produced no further output
    CompileC /Users/abcdefg/Library/Developer/Xcode/DerivedData/Runner-dnbujvtnlrnqewcajznimcqfcgbf/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/plaid_flutter.build/Objects-normal/arm64/PlaidFlutterPlugin.o /Users/abcdefg/Code/flutter/.pub-cache/hosted/pub.dartlang.org/plaid_flutter-2.1.4/ios/Classes/PlaidFlutterPlugin.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
Exited (sigterm)
```

**Comment by ShantanuJoshi** [comment]
I was getting the exact same issue and noticed that my build OS version # were mismatched. I'd recommend setting `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'` in your podfile for each library as well as explicitly defining `platform :ios, '12.0'` at the top.

I'm using the following code at the end of my podfile:
```post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
   end
  end
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
 end
 ```

**Comment by arslankaleem7229** [comment]
> I was getting the exact same issue and noticed that my build OS version # were mismatched. I'd recommend setting `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'` in your podfile for each library as well as explicitly defining `platform :ios, '12.0'` at the top.
> 
> I'm using the following code at the end of my podfile:
> 
> ```
>   installer.pods_project.targets.each do |target|
>    target.build_configurations.each do |config|
>     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
>    end
>   end
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>   end
>  end
> ```

Yes I resolved that issue. Thanks
