### ISSUE TITLE
Add multiple countries

### ISSUE THREAD

**Issue by StanfordLin** [jorgefspereira/plaid_flutter#6]
It would be really awesome if countryCodes can be added to support more countries

https://github.com/plaid/react-native-plaid-link-sdk
https://plaid.com/docs/faq/#does-plaid-support-international-bank-accounts-
      'countryCodes': ['CA']

**Comment by jorgefspereira** [comment]
Hi @StanfordLin. Added the countryCode support on the new 0.2.5 version. Thank you for the suggestion.
