### ISSUE TITLE
'Close' method not implemented

### ISSUE THREAD

**Issue by avi-barel-bv** [jorgefspereira/plaid_flutter#60]
Hey @jorgefspereira,

I'm listening to the events from Plaid, and in some scenarios I need to close the Plaid window and return to my app.
In iOS this works great by calling `PlaidLink.close();`
However, in Android it doesn't work and I noticed the close method has no implementation.
Is there a reason for that? How can I add the close logic?

Thanks,
Avi

**Comment by jorgefspereira** [comment]
Hi @avi-barel-bv , You're right. I'll add the close logic in the upcoming release.

**Comment by avi-barel-bv** [comment]
Thanks 👍
