### ISSUE TITLE
blocked by CORS policy Issue in android version 8

### ISSUE THREAD

**Issue by PrabavathiKalidoss** [jorgefspereira/plaid_flutter#65]
We are using plaid_flutter: ^2.2.0 version.But we still have a issue on android version 8 like,
Access to font at 'https://cdn.plaid.com/link/2.0.1097/assets/fonts/cern-regular.woff2' from origin 'https://secure.plaid.com/' has been blocked by CORS policy

Help me to fix this issue.

**Comment by jorgefspereira** [comment]
Hi @PrabavathiKalidoss. This seems an issue related with the Plaid Link SDK itself and not this flutter wrapper. Please give a try to the newest update version 2.2.1 (has the latest sdks) to see if the issue is fixed. If the issue persists, try to report on plaid issue tracker for android.
