### ISSUE TITLE
No browser redirect

### ISSUE THREAD

**Issue by k5924** [jorgefspereira/plaid_flutter#67]
Ive implemented plaid so the part where a user can choose the bank they want to connect to works but, when I click continue which normally redirects to the browser, no webpage is opened in the browser. I know its not a webview issue as other webviews in my application work fine. Any ideas?

I thought it might be a permissions issue but the plaid frontend loads in the application and the application has internet permissions. My compiledSdkVersion is 31, is there anything else I need to add to the AndroidManifest.xml to make the application work correctly? Im using the most up to date version of the plaid_flutter package

**Comment by jorgefspereira** [comment]
As per description, it seems very similar to issue #82.

I left here (https://github.com/jorgefspereira/plaid_flutter/issues/82#issuecomment-1318830133) a possible solution for the problem. Feel free to reopen or pull request an issue fix if you found the problem's root.
