### ISSUE TITLE
Callback does not execute

### ISSUE THREAD

**Issue by CocoaJerry** [jorgefspereira/plaid_flutter#70]
device: samsung
sdk-version: 2.2.2

When the app goes into the background for a while, and then reopen the app and click the auth button, we successfully complete the auth operation, but there is no output from the callback. but the other callback we added goes well. Is there any variable being freed during this period or something else?

**Comment by CocoaJerry** [comment]
![image](https://user-images.githubusercontent.com/15193239/178292254-89fc0bc4-e1d2-490b-a371-32a7ab3cde0d.png)
Just these callbacks. They are basically the same as the demo implementation. I only add some callback handling. When the app enters the background for about half an hour, the problem I said will appear.

**Comment by devabdiel** [comment]
We also are facing the same issue, not after resuming the app from brackground, just the `onSuccess`, `onEvent` and `onExit` callbacks are not executed even if we close and reopen the link.
```dart
abstract class PlaidClient {
  LinkTokenConfiguration configurate(String token);
  Future<void> open(
    LinkTokenConfiguration configuration, {
    required void Function(String, LinkSuccessMetadata) onSuccess,
    void Function(LinkError?, LinkExitMetadata)? onExit,
  });
  Future<void> close();
}

@LazySingleton(
  as: PlaidClient,
  env: [Env.development, Env.production],
)
class PlaidClientImpl implements PlaidClient {
  @override
  LinkTokenConfiguration configurate(String token) {
    return LinkTokenConfiguration(
      token: token,
    );
  }

  @override
  Future<void> open(
    LinkTokenConfiguration configuration, {
    required void Function(String, LinkSuccessMetadata) onSuccess,
    void Function(LinkError?, LinkExitMetadata)? onExit,
  }) async {
    await PlaidLink.open(configuration: configuration);

    PlaidLink.onSuccess(onSuccess);
    if (onExit != null) PlaidLink.onExit(onExit);
  }

  @override
  Future<void> close() {
    return PlaidLink.close();
  }
}
```

**Comment by jorgefspereira** [comment]
I changed this callback pattern to stream events. Hopefully this fixes the issue.

**Comment by CocoaJerry** [comment]
I will update the sdk version and check if the issue still exists. Thank you
