### ISSUE TITLE
Plaid flow OAuth app-to-app IOS not rediretcing back to the app

### ISSUE THREAD

**Issue by MarinMijalic** [jorgefspereira/plaid_flutter#75]
Hello,

I'm having trouble with the implmentation of the OAuth app-to-app on IOS devices. Basically, browser OAuth is working as intended but when I test app-to-app OAuth I am not redirected back to the app I stay on the blank page set up for redirection.  Flow completes in the background and selected accounts are present in the app, you just need to enter them into the app manually.

Marin

**Comment by gvsakki** [comment]
I am also facing the same issue. Any update on this?

**Comment by jorgefspereira** [comment]
Hi @gvsakki, can you better describe the use case so I can test here properly?

**Comment by dlovric01** [comment]
Hi @gvsakki, the issue we had was related to the apple-app-association-file, once we set it up properly redirect worked.

**Comment by gvsakki** [comment]
Can u give a sample of ur apple-app-association-file? @dlovric01

**Comment by dlovric01** [comment]
{
    "applinks": {
        "details": [
            {
                "appIDs": [
                    "TeamID.bundleId",
                ],
                "components": [
                    {
                        "/": "/blank"
                    }
                ]
            }
        ]
    }
}
