### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.plaid.internal.LinkRedirectActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by BetulComak** [jorgefspereira/plaid_flutter#76]
The link flow initializes as expected on the phone and I am redirected to the Bank (Wise UK) but on completion and when the screen shows "All done", I am not redirected back to my app, the phone crashes - and I get the following message:

`Shutting down VM

E/AndroidRuntime( 3826): FATAL EXCEPTION: main

E/AndroidRuntime( 3826): Process: com.my.app, PID: 3826

E/AndroidRuntime( 3826): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.plaid.internal.LinkRedirectActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`

 flutter:3.0.5
 plaid_flutter: ^2.2.2

**NOTE:** https://github.com/plaid/plaid-link-android/issues/148  not working to me

**Comment by sezer** [comment]
Any update about this one? Getting same error. Addin theme to manifest did not work.

**Comment by btrautmann** [comment]
@sezer I've explained the solution in https://github.com/plaid/plaid-link-android/issues/148#issuecomment-1293521663, and @BetulComak I think that should work for you as well.

**Comment by jorgefspereira** [comment]
Thank you @btrautmann for point to the solution.

**Comment by btrautmann** [comment]
@jorgefspereira just a heads up, this should really be remediated on the plaid SDK side. Overriding the theme on the host app's manifest shouldn't be necessary IMO.
