### ISSUE TITLE
PlaidLink - update existing item

### ISSUE THREAD

**Issue by jchrisp** [jorgefspereira/plaid_flutter#8]
Hi, is it possible to pass in an existing `public_token` in order to re-link an existing item? I believe you would only need to pass in the `token` param. See below.

plaid.com/docs/#updating-items-via-link

![Screen Shot 2020-06-11 at 9 33 46 AM](https://user-images.githubusercontent.com/1140960/84391240-b2cee800-abc6-11ea-93dd-c35ad08b2268.png)

Thanks!

**Comment by jorgefspereira** [comment]
Hi @jchrisp. Thank you for the feedback. I've updated the plugin with a new publicToken argument to enable the re-link of an existing item. Please check out the version 0.3.0 and if something is wrong feel free to reopen this issue.
