### ISSUE TITLE
Is there anyway to reopen the plaid link upon an o auth redirect for web? 

### ISSUE THREAD

**Issue by jay2jp** [jorgefspereira/plaid_flutter#80]
Im watching the plaid tutorial for the web SDK and when handling the oauth redirect they specify recievedRedirectUri here. I cant seem to find a way to reopen the plaidlink with this library when coming back from oauth on mobile web. Is this not possible with this package? 
![image](https://user-images.githubusercontent.com/17814331/200044093-daa86464-1122-4c4c-a410-d328de169b04.png)

**Comment by jay2jp** [comment]
Hey, so I wrote my own fork of the library that has the functionality for this if anyone is looking for it you can just use it from here 
https://github.com/jay2jp/plaid_flutter_cambio. I didn't make a pull request since it is a bit hackey since and not well implemented but to use it all you have to do use is use  LinkTokenConfigurationRedir instead of LinkTokenConfiguration. within that, there is a field to let you populate the redirect URI called receivedRedirectUri and you can just proceed from there. 
Import it like i have below and then you can just use it like you use the normal one, however, you should only use the redir version on the web page that handles the oauth redirect on flutter web. 
```  #plaid_flutter: ^2.2.1 old package i used 
  plaid_flutter:
    git:
      url: https://github.com/jay2jp/plaid_flutter_cambio.git
      ref: master
      publish_to: 'none'

**Comment by jorgefspereira** [comment]
Hi @jay2jp, I'll take a look to your fork and implement this feature for the web 👍

**Comment by jorgefspereira** [comment]
Published version 3.0.0 with `receivedRedirectUri` option for the web.

**Comment by Miko2x** [comment]
Hi @jorgefspereira 
Is it the same for the web to put `window.location.href` in the `receivedRedirectUri`? I imported the window from `dart:html`

<img width="560" alt="image" src="https://user-images.githubusercontent.com/41611726/210584741-d7c38ed6-11e1-476a-87f6-2f2a4d698138.png">

**Comment by jorgefspereira** [comment]
@Miko2x yes
