### ISSUE TITLE
No browser redirect after clicking "continue" on the last page.

### ISSUE THREAD

**Issue by Magadya** [jorgefspereira/plaid_flutter#82]
Development env. 
Android.

I have problem with redirect after clicking "continue" on the last page. After clicking the button, an attempt is made to redirect to the URL: https://analytics.plaid.com/sentry/api/5/store/?sentry_version=7&sentry_client=raven-js/3.22.4&sentry_key=70ddbe2c1d3e40299887a99df1d4828f

by nothing else.

https://user-images.githubusercontent.com/52001214/201617807-8c49659d-8c90-4db7-94a5-acad6adea3a3.mp4

**Comment by jorgefspereira** [comment]
Hi @Magadya, it seems you are missing two configuration steps :
1 - Add your android package name in your developer dashboard (https://dashboard.plaid.com/team/api)
2 - Request your link token with the option 'android_package_name' (https://plaid.com/docs/api/tokens/#link-token-create-request-android-package-name)

Hopefully this fixes your issue.
