### ISSUE TITLE
iOS release build runtime crash (Library not loaded: @rpath/LinkKit.framework/LinkKit) plugin version 3.0.0

### ISSUE THREAD

**Issue by qqmikey** [jorgefspereira/plaid_flutter#85]
Referenced from: <5D68FCC9-4FC5-3B1C-B501-2AC76D0C64F2> /private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Runner
  Reason: tried: '/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2), '/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2), '/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/private/preboot/Cryptexes/OS@rpath/LinkKit.framework/LinkKit' (errno=2), '/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2), '/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2), '/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/private/var/containers/Bundle/Application/CECB9970-3772-4447-9C7F-D2A07C339799/Runner.app/Frameworks/LinkKit.framework/LinkKit' (errno=2), '/System/Library/Frameworks/LinkKit.framework/LinkKit' (errno=2, not in dyld cache)

**Comment by jorgefspereira** [comment]
Hi @qqmikey what version of cocoapods are you running?

**Comment by qqmikey** [comment]
@jorgefspereira 1.11.3

**Comment by jorgefspereira** [comment]
Try to add LinkKit.xcframework to the framework library settings of the Runner project, to see if the problem persists.

The problem looks very similar to this https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/608 where the fix seems to be related to your ruby installation. 

https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/608#issuecomment-1336043290

**Comment by qqmikey** [comment]
@jorgefspereira `add LinkKit.xcframework to the framework library settings of the Runner project` solves the problem!

**Comment by qqmikey** [comment]
@jorgefspereira  should LinkKit.xcframework be specified in plaid_flutter Pod's `Frameworks and Libraries`? i don't have one here
