### ISSUE TITLE
Feature to retrieve institution logo

### ISSUE THREAD

**Issue by luisforditch** [jorgefspereira/plaid_flutter#86]
Plaid sends metadata for the institution logo but it's not being capture in the metadata object, it would be useful to have.

Something like this

void _onSuccess(LinkSuccess event) {
    final token = event.publicToken;
    final metadata = event.metadata.description();
    print("onSuccess: $token, metadata: $metadata");
    // THIS: final logoURL = event.metadata.institution.logo;
    setState(() => _successObject = event);
  }

**Comment by jorgefspereira** [comment]
Hi @luisforditch, I do not see any logo metadata being sent by Plaid. Can you point to the [documentation](https://plaid.com/docs) where is referred?
