### ISSUE TITLE
Unable to retrieve PUBLICTOKEN on Android when connecting crypto exchange ( Binance US )

### ISSUE THREAD

**Issue by dlovric01** [jorgefspereira/plaid_flutter#88]
Hi @jorgefspereira, there is an issue when trying to retrieve a **Public token** on Android devices when connecting to a crypto exchange, in this case, Binance US.

Below are logs of events on both Android and iOS.

**iOS**
```
[log] PLAIDEVENT OPEN
[log] PLAIDMETADATA
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA
[log] PLAIDEVENT SEARCH_INSTITUTION
[log] PLAIDMETADATA
[log] PLAIDEVENT SEARCH_INSTITUTION
[log] PLAIDMETADATA
[log] PLAIDEVENT SELECT_INSTITUTION
[log] PLAIDMETADATA ins_132612
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA ins_132612
[log] PLAIDEVENT SUBMIT_MFA
[log] PLAIDMETADATA ins_132612
[log] PLAIDEVENT SUBMIT_MFA
[log] PLAIDMETADATA ins_132612
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA ins_132612

[log] PLAIDEVENT HANDOFF
[log] PLAIDMETADATA ins_132612

[log] PUBLICTOKEN public-****************************************
```

**Android**
```
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA
[log] PLAIDEVENT OPEN
[log] PLAIDMETADATA
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA
[log] PLAIDEVENT SEARCH_INSTITUTION
[log] PLAIDMETADATA
[log] PLAIDEVENT SELECT_INSTITUTION
[log] PLAIDMETADATA ins_132612
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA ins_132612
[log] PLAIDEVENT SUBMIT_MFA
[log] PLAIDMETADATA ins_132612
[log] PLAIDEVENT SUBMIT_MFA
[log] PLAIDMETADATA ins_132612
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA ins_132612

[log] PLAIDEVENT HANDOFF
[log] PLAIDMETADATA ins_132612
```

On iOS, we are retrieving **public token** right after PLAIDEVENT HANDOFF, but on android, the process just stops and we do not receive any form of information.

Note:
This only happens on a crypto exchange.
It has been tested on both android and iOS real devices and simulators, and Android devices always seem to fail in this case.

**Issue**
![Screenshot 2022-12-22 at 11 15 52](https://user-images.githubusercontent.com/95619424/209112147-8f1b231e-730d-4a05-bf74-f5ff98103805.png)

It seems like **mask** is not being received inside metadata for Android devices on a crypto exchange.

![Screenshot 2022-12-22 at 11 26 15](https://user-images.githubusercontent.com/95619424/209115024-da6e515d-8781-41a2-92a5-fe379262444d.png)

This field is not required in Plaid documentation but it is visible that it is required inside the plaid_flutter package. Is there a reason for that?

We are using **plaid_flutter 2.2.0**

**Update**:
After upgrading to plaid_flutter 3.0.0 the problem still exists

**Comment by dlovric01** [comment]
@jorgefspereira can you please look into it? Thank you!

**Comment by jorgefspereira** [comment]
@dlovric01 yes! I'll check it today.

**Comment by jorgefspereira** [comment]
version 3.0.1 should fix the problem.
