### ISSUE TITLE
OnSuccess triggered multiple times

### ISSUE THREAD

**Issue by MarinMijalic** [jorgefspereira/plaid_flutter#91]
Hi @jorgefspereira, there is an issue where OnSuccess is triggered multiple times.
 
LOGS
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA
[log] PLAIDEVENT OPEN
[log] PLAIDMETADATA
[log] PLAIDEVENT OPEN
[log] PLAIDMETADATA
[log] PLAIDEVENT SELECT_INSTITUTION
[log] PLAIDMETADATA ins_115616
[log] PLAIDEVENT SELECT_INSTITUTION
[log] PLAIDMETADATA ins_115616
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA ins_115616
[log] PLAIDEVENT TRANSITION_VIEW
[log] PLAIDMETADATA ins_115616
[log] PLAIDEVENT HANDOFF
[log] PLAIDMETADATA ins_115616
[log] PLAIDEVENT HANDOFF
[log] PLAIDMETADATA ins_115616

[log] PUBLICTOKEN public-sandbox-********************************************
[log] PUBLICTOKEN public-sandbox-********************************************

The last log of the public token is on top of the onSuccess method. They happen milliseconds apart.

Using version 3.0.1. 

On version 2.2.2 method OnSuccess is not triggered multiple times.

**Comment by jorgefspereira** [comment]
Hi @MarinMijalic, can you replicate consistently this issue? can you provide more info so that i can reproduce on my side the exact same scenario?

**Comment by ujwalbasnet1** [comment]
@MarinMijalic how did you solve the issue?

**Comment by gferreirakalshi** [comment]
If you are having this, you are probably calling the stream listener twice.
